# Generated by Django 2.1.7 on 2019-04-23 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_postgis'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coordsfreq',
            options={'managed': False, 'ordering': ['frequency']},
        ),
    ]
