# Generated by Django 2.1.7 on 2019-04-23 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190423_1953'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coordsfreq',
            options={'managed': False, 'ordering': ['-frequency']},
        ),
    ]
